import React from "react";
import styles from "./CoursesScheduleTable.module.scss";

const CoursesScheduleTable = () => (
  <table className={styles.coursesTable}>
    <thead>
      <tr>
        <td>Horário</td>
        <td>Sábado</td>
        <td>Domingo</td>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>9:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>9:30</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>10:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>10:30</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>11:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>11:30</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>12:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>12:30</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>13:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>13:30</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>14:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>14:30</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>15:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>15:30</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>16:00</td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>16:30</td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
);

export default CoursesScheduleTable;
